[package]
name = "tokio_console_demo"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["--cfg", "tokio_unstable"]

[dependencies]
anyhow = "1.0.71"
console-subscriber = "0.1.9"
tokio = { version = "1.28.2", features = ["full"] }
tracing = "0.1.37"
