[package]
name = "login_hashmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
login_lib_hashmap = { path = "../login_lib_hashmap" }